language: java
script: mvn clean verify
jdk:
  - openjdk14
  - oraclejdk14

services:
  - postgresql
before_script:
  - psql -c 'create database PollApp_test;' -U test
env:
  global:
    - PGPORT=5433
